'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

var handler = require('./handler/handler.js');
var loop = require('./plugins/jsx/loop/loop.js');
var portal = require('./plugins/jsx/portal/portal.js');
var context = require('./plugins/jsx/context/context.js');
var slots = require('./plugins/jsx/slots/slots.js');
var slot = require('./plugins/jsx/slot/slot.js');
var domAsync = require('./plugins/domAsync/domAsync.js');
var domIterable = require('./plugins/domIterable/domIterable.js');
var domJSX = require('./plugins/domJSX/domJSX.js');
var domNode = require('./plugins/domNode/domNode.js');
var domFn = require('./plugins/domFn/domFn.js');
var domText = require('./plugins/domText/domText.js');
var domAsyncIterable = require('./plugins/domAsyncIterable/domAsyncIterable.js');
var Ref = require('./utils/Ref/Ref.js');
var dom = require('./utils/dom/dom.js');
var getParent = require('./utils/getParent/getParent.js');
var setParent = require('./utils/setParent/setParent.js');
var useComment = require('./utils/useComment/useComment.js');
var constants = require('./constants.js');



exports.JSXPlugins = handler.JSXPlugins;
exports.arrayPlugins = handler.arrayPlugins;
exports["default"] = handler.handler;
exports.fnPlugins = handler.fnPlugins;
exports.handler = handler.handler;
exports.nodePlugins = handler.nodePlugins;
exports.numberPlugins = handler.numberPlugins;
exports.objectPlugins = handler.objectPlugins;
exports.promisePlugins = handler.promisePlugins;
exports.stringPlugins = handler.stringPlugins;
exports.LoopItem = loop.LoopItem;
exports.loop = loop.loop;
exports.portal = portal.portal;
exports.Context = context.Context;
exports.context = context.context;
exports.createContextHandler = context.createContextHandler;
exports.slots = slots.slots;
exports.slotsContext = slots.slotsContext;
exports.getSlots = slot.getSlots;
exports.slot = slot.slot;
exports.domAsync = domAsync.domAsync;
exports.domIterable = domIterable.domIterable;
exports.domJSX = domJSX.domJSX;
exports.domNode = domNode.domNode;
exports.domFn = domFn.domFn;
exports.domText = domText.domText;
exports.domAsyncIterable = domAsyncIterable.domAsyncIterable;
exports.Ref = Ref.Ref;
exports.after = dom.after;
exports.append = dom.append;
exports.before = dom.before;
exports.clear = dom.clear;
exports.prepend = dom.prepend;
exports.remove = dom.remove;
exports.getParent = getParent.getParent;
exports.setParent = setParent.setParent;
exports.useComment = useComment.useComment;
exports.PARENT = constants.PARENT;
