'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

require('./handler/index.js');
require('./plugins/index.js');
require('./utils/index.js');
require('./hooks/index.js');
var constants = require('./constants.js');
require('./types.js');
require('./test/index.js');
var handler = require('./handler/handler.js');
var loop = require('./plugins/jsx/loop/loop.js');
var portal = require('./plugins/jsx/portal/portal.js');
var router = require('./plugins/jsx/router/router.js');
var link = require('./plugins/jsx/link/link.js');
var delay = require('./plugins/jsx/delay/delay.js');
var domAsync = require('./plugins/domAsync/domAsync.js');
var domIterable = require('./plugins/domIterable/domIterable.js');
var domJSX = require('./plugins/domJSX/domJSX.js');
var domNode = require('./plugins/domNode/domNode.js');
var domFn = require('./plugins/domFn/domFn.js');
var domText = require('./plugins/domText/domText.js');
var domAsyncIterable = require('./plugins/domAsyncIterable/domAsyncIterable.js');
var Ref = require('./utils/Ref/Ref.js');
var dom = require('./utils/dom/dom.js');
var getParent = require('./utils/getParent/getParent.js');
var setParent = require('./utils/setParent/setParent.js');
var getComment = require('./utils/getComment/getComment.js');
var stringifySearch = require('./utils/stringifySearch/stringifySearch.js');
var parseSearch = require('./utils/parseSearch/parseSearch.js');
var dif = require('./utils/dif/dif.js');
var use = require('./utils/use/use.js');
var useParent = require('./hooks/useParent/useParent.js');
var useStyle = require('./hooks/useStyle/useStyle.js');
var useShow = require('./hooks/useShow/useShow.js');
var getHTML = require('./test/getHTML/getHTML.js');
var render = require('./test/render/render.js');



exports.PARENT = constants.PARENT;
exports.JSXPlugins = handler.JSXPlugins;
exports.arrayPlugins = handler.arrayPlugins;
exports["default"] = handler.handler;
exports.fnPlugins = handler.fnPlugins;
exports.handler = handler.handler;
exports.nodePlugins = handler.nodePlugins;
exports.numberPlugins = handler.numberPlugins;
exports.objectPlugins = handler.objectPlugins;
exports.promisePlugins = handler.promisePlugins;
exports.stringPlugins = handler.stringPlugins;
exports.LoopItem = loop.LoopItem;
exports.loop = loop.loop;
exports.portal = portal.portal;
exports.getRoute = router.getRoute;
exports.getStrongRoute = router.getStrongRoute;
exports.history = router.history;
exports.parsedPath = router.parsedPath;
exports.parsedSearch = router.parsedSearch;
exports.pathDeep = router.pathDeep;
exports.router = router.router;
exports.routerContext = router.routerContext;
exports.routes = router.routes;
exports.routesIsh = router.routesIsh;
exports.useRoute = router.useRoute;
exports.defaultClass = link.defaultClass;
exports.link = link.link;
exports.delay = delay.delay;
exports.delayContext = delay.delayContext;
exports.useHidden = delay.useHidden;
exports.domAsync = domAsync.domAsync;
exports.domIterable = domIterable.domIterable;
exports.domJSX = domJSX.domJSX;
exports.domNode = domNode.domNode;
exports.domFn = domFn.domFn;
exports.domText = domText.domText;
exports.domAsyncIterable = domAsyncIterable.domAsyncIterable;
exports.Ref = Ref.Ref;
exports.after = dom.after;
exports.append = dom.append;
exports.before = dom.before;
exports.clear = dom.clear;
exports.prepend = dom.prepend;
exports.remove = dom.remove;
exports.getParent = getParent.getParent;
exports.setParent = setParent.setParent;
exports.getComment = getComment.getComment;
exports.stringifySearch = stringifySearch.stringifySearch;
exports.parseSearch = parseSearch.parseSearch;
exports.dif = dif.dif;
exports.use = use.use;
exports.useParent = useParent.useParent;
exports.getStyles = useStyle.getStyles;
exports.style = useStyle.style;
exports.useShow = useShow.useShow;
exports.getHTML = getHTML.getHTML;
exports.render = render.render;
